
var tracklistAudio = [
	{
		fileName: 'SWPP00119L.mp3',
		trackNumber: 1,
		artistName: 'Stephanie Whitehead',
		trackTitle: 'The handsome prince',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '02:53',
	},
	{
		fileName: 'SWPP00219L.mp3',
		trackNumber: 2,
		artistName: 'David Appleton',
		trackTitle: 'The rescue',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '02:17',
	},
	{
		fileName: 'SWPP00319L.mp3',
		trackNumber: 3,
		artistName: 'Gina McLeod',
		trackTitle: 'The celestial harp',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '02:21',
	},
	{
		fileName: 'SWPP00419L.mp3',
		trackNumber: 4,
		artistName: 'Shane Considine',
		trackTitle: 'Dawn',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '02:00',
	},
	{
		fileName: 'SWPP00519L.mp3',
		trackNumber: 5,
		artistName: 'Helen Havens',
		trackTitle: 'Floating through space',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '01:20',
	},
	{
		fileName: 'SWPP00619L.mp3',
		trackNumber: 6,
		artistName: 'Debra Diaz',
		trackTitle: 'Milky way',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '02:38',
	},
	{
		fileName: 'SWPP00719L.mp3',
		trackNumber: 7,
		artistName: 'Sharon Moreno',
		trackTitle: 'Star gazing',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '04:56',
	},
	{
		fileName: 'SWPP00819L.mp3',
		trackNumber: 8,
		artistName: 'William Green',
		trackTitle: 'Summit',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '03:24',
	},
	{
		fileName: 'SWPP00919L.mp3',
		trackNumber: 9,
		artistName: 'William Todd',
		trackTitle: 'Sunrise',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '01:58',
	},
	{
		fileName: 'SWPP01019L.mp3',
		trackNumber: 10,
		artistName: 'Epifania Pilcher',
		trackTitle: 'Warm glow',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '03:45',
	},
	{
		fileName: 'SWPP01119L.mp3',
		trackNumber: 11,
		artistName: 'David Padilla',
		trackTitle: 'Take it all in',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '01:22',
	},
	{
		fileName: 'SWPP01219L.mp3',
		trackNumber: 12,
		artistName: 'Jennifer Vercher',
		trackTitle: 'Technological',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '02:13',
	},
	{
		fileName: 'SWPP01319L.mp3',
		trackNumber: 13,
		artistName: 'Richard Tong',
		trackTitle: 'Silent threat',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '01:55',
	},
	{
		fileName: 'SWPP01419L.mp3',
		trackNumber: 14,
		artistName: 'Kathy Rainey',
		trackTitle: 'Standing tall',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '03:10',
	},
	{
		fileName: 'SWPP01519L.mp3',
		trackNumber: 15,
		artistName: 'Frances Scheuerman',
		trackTitle: 'Oceans at rest',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '01:27',
	},
	{
		fileName: 'SWPP01619L.mp3',
		trackNumber: 16,
		artistName: 'Ronald Wilson',
		trackTitle: 'Gliding',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '03:05',
	},
	{
		fileName: 'SWPP01719L.mp3',
		trackNumber: 17,
		artistName: 'Patricia Stuart',
		trackTitle: 'Good times',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '04:43',
	},
	{
		fileName: 'SWPP01819L.mp3',
		trackNumber: 18,
		artistName: 'Herbert Miller',
		trackTitle: 'Lazy days',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '04:40',
	},
	{
		fileName: 'SWPP01919L.mp3',
		trackNumber: 19,
		artistName: 'Daniel Morgan',
		trackTitle: 'Enchanting',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '03:06',
	},
	{
		fileName: 'SWPP02019L.mp3',
		trackNumber: 20,
		artistName: 'Joseph McCall',
		trackTitle: 'Comfort blanket',
		albumName: 'Spoken Word Product',
		trackYear: '2019',
		trackLength: '03:17',
	}
];