
var tracklistVideo = [
	{
		fileName: 'SWPP00119P.mp4',
		trackNumber: 1,
		artistName: 'Larry Bennet',
		trackTitle: 'Burning charcoal fire',
		albumName: 'Spoken Word Product Name',
		trackYear: '2019',
		trackLength: '00:05',
	},
	{
		fileName: 'SWPP00219P.mp4',
		trackNumber: 2,
		artistName: 'Karen Oswalt',
		trackTitle: 'Coffee in the morning',
		albumName: 'Spoken Word Product Name',
		trackYear: '2019',
		trackLength: '00:05',
	},
	{
		fileName: 'SWPP00319P.mp4',
		trackNumber: 3,
		artistName: 'Jessica Morton',
		trackTitle: 'Ocean sunset view',
		albumName: 'Spoken Word Product Name',
		trackYear: '2019',
		trackLength: '00:05',
	},
	{
		fileName: 'SWPP00419P.mp4',
		trackNumber: 4,
		artistName: 'George Lokken',
		trackTitle: 'Sunset',
		albumName: 'Spoken Word Product Name',
		trackYear: '2019',
		trackLength: '00:05',
	},
	{
		fileName: 'SWPP00519P.mp4',
		trackNumber: 5,
		artistName: 'Ralph Aden',
		trackTitle: 'Blue jellyfish',
		albumName: 'Spoken Word Product Name',
		trackYear: '2019',
		trackLength: '00:05',
	},
	{
		fileName: 'SWPP00619P.mp4',
		trackNumber: 6,
		artistName: 'Viola Stradley',
		trackTitle: 'Auror Borealis',
		albumName: 'Spoken Word Product Name',
		trackYear: '2019',
		trackLength: '00:04',
	},
	{
		fileName: 'SWPP00719P.mp4',
		trackNumber: 7,
		artistName: 'Eileen Beyer',
		trackTitle: 'Butterlfy flying away from a flower',
		albumName: 'Spoken Word Product Name',
		trackYear: '2019',
		trackLength: '00:05',
	},
	{
		fileName: 'SWPP00819P.mp4',
		trackNumber: 8,
		artistName: 'Tobias Bjorkli',
		trackTitle: 'Fogs over the mountain',
		albumName: 'Spoken Word Product Name',
		trackYear: '2019',
		trackLength: '00:05',
	},
	{
		fileName: 'SWPP00919P.mp4',
		trackNumber: 9,
		artistName: 'Miriam Epsacio',
		trackTitle: 'The night sky',
		albumName: 'Spoken Word Product Name',
		trackYear: '2019',
		trackLength: '00:04',
	},
	{
		fileName: 'SWPP01019P.mp4',
		trackNumber: 10,
		artistName: 'Tom Fisk',
		trackTitle: 'A vast wheat field',
		albumName: 'Spoken Word Product Name',
		trackYear: '2019',
		trackLength: '00:05',
	}
];